//HW Arrow functions


//task 1
const addExclamation = str => str + "!";
/******************************************************************************/
//task 2
const reverseWords = sentence => sentence.split(" ").reverse().join(" ");
/*****************************************************************************  **/
//task3
const squareAll = arr => arr.map(x => x * x);
/****************************************************************************** **/
//task4
const filterNames = (names, minLength) => names.filter(name => name.length > minLength);
/****************************************************************************** **/
//task5
const allPositive = numbers => numbers.every(num => num > 0);
/******************************************************************************* **/


